INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline, bio) VALUES ('Marija','Yamada','1@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline,bio) VALUES ('Mamoun','Nevin','2@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline,bio) VALUES ('Alice','McPhee','3@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline,bio) VALUES ('Sergio','Holm','4@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline,bio) VALUES ('Klemen','Hackett','5@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline,bio) VALUES ('Apollonia','Beitel','6@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline,bio) VALUES ('Gvidas','Antonov','7@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline,bio) VALUES ('Titus','Lukeson','8@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline,bio) VALUES ('Pylyp','Gates','9@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
INSERT INTO junior_devs (first_name,last_name,email,password,phone_number, headline,bio) VALUES ('Senan','Thompson','10@junior.com','123','306.821.3553','Full-stack Developer', 'My bio');
